# permissions for end users to edit mservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mservice-editor-role
rules:
- apiGroups:
  - test.r.kubebuilder.io
  resources:
  - mservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.r.kubebuilder.io
  resources:
  - mservices/status
  verbs:
  - get
