# permissions for end users to view mservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mservice-viewer-role
rules:
- apiGroups:
  - test.r.kubebuilder.io
  resources:
  - mservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.r.kubebuilder.io
  resources:
  - mservices/status
  verbs:
  - get
