apiVersion: test.r.kubebuilder.io/v1
kind: MService
metadata:
  name: srv-lm-test
  namespace: liming-test
spec:
  # Add fields here
  ingress:
    -
      scheme: http
      host: www.baidu.com
      path: /
  ports:
    -
      port: 80
      targetPort: 80
      protocol: TCP
  Secret:
    username: rock
    password: ontrol
